/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.1
processor: MK66FX1M0xxx18
package_id: MK66FX1M0VMD18
mcu_data: ksdk2_0
processor_version: 4.0.0
pin_labels:
- {pin_num: A1, pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/SDRAM_CKE/FTM0_FLT1/SPI1_SIN, label: led7, identifier: led7}
- {pin_num: A2, pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT, label: led6, identifier: led6}
- {pin_num: A3, pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/SDRAM_A9/EWM_OUT_b/SPI1_SCK, label: led5, identifier: led5}
- {pin_num: B4, pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/SDRAM_A11/I2C0_SDA, label: led3, identifier: led3}
- {pin_num: A4, pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/SDRAM_A10/EWM_IN/SPI1_PCS0, label: led4, identifier: led4}
- {pin_num: C4, pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/SDRAM_A12/I2C0_SCL, label: led2, identifier: led2}
- {pin_num: D4, pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, label: led1, identifier: led1}
- {pin_num: A5, pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, label: led0, identifier: led0}
- {pin_num: D8, pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/SDRAM_A18/CMP0_OUT/FTM0_CH2, label: brd_led, identifier: brd_led}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "fsl_gpio.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: A5, peripheral: GPIOD, signal: 'GPIO, 0', pin_signal: PTD0/LLWU_P12/SPI0_PCS0/UART2_RTS_b/FTM3_CH0/FB_ALE/FB_CS1_b/FB_TS_b, direction: OUTPUT}
  - {pin_num: D4, peripheral: GPIOD, signal: 'GPIO, 1', pin_signal: ADC0_SE5b/PTD1/SPI0_SCK/UART2_CTS_b/FTM3_CH1/FB_CS0_b, direction: OUTPUT}
  - {pin_num: C4, peripheral: GPIOD, signal: 'GPIO, 2', pin_signal: PTD2/LLWU_P13/SPI0_SOUT/UART2_RX/FTM3_CH2/FB_AD4/SDRAM_A12/I2C0_SCL, direction: OUTPUT}
  - {pin_num: B4, peripheral: GPIOD, signal: 'GPIO, 3', pin_signal: PTD3/SPI0_SIN/UART2_TX/FTM3_CH3/FB_AD3/SDRAM_A11/I2C0_SDA, direction: OUTPUT}
  - {pin_num: A4, peripheral: GPIOD, signal: 'GPIO, 4', pin_signal: PTD4/LLWU_P14/SPI0_PCS1/UART0_RTS_b/FTM0_CH4/FB_AD2/SDRAM_A10/EWM_IN/SPI1_PCS0, direction: OUTPUT}
  - {pin_num: A3, peripheral: GPIOD, signal: 'GPIO, 5', pin_signal: ADC0_SE6b/PTD5/SPI0_PCS2/UART0_CTS_b/UART0_COL_b/FTM0_CH5/FB_AD1/SDRAM_A9/EWM_OUT_b/SPI1_SCK,
    direction: OUTPUT}
  - {pin_num: A2, peripheral: GPIOD, signal: 'GPIO, 6', pin_signal: ADC0_SE7b/PTD6/LLWU_P15/SPI0_PCS3/UART0_RX/FTM0_CH6/FB_AD0/FTM0_FLT0/SPI1_SOUT, direction: OUTPUT}
  - {pin_num: A1, peripheral: GPIOD, signal: 'GPIO, 7', pin_signal: PTD7/CMT_IRO/UART0_TX/FTM0_CH7/SDRAM_CKE/FTM0_FLT1/SPI1_SIN, direction: OUTPUT}
  - {pin_num: D8, peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: PTC5/LLWU_P9/SPI0_SCK/LPTMR0_ALT2/I2S0_RXD0/FB_AD10/SDRAM_A18/CMP0_OUT/FTM0_CH2, direction: OUTPUT}
  - {pin_num: K8, peripheral: TPM1, signal: 'CH, 0', pin_signal: ADC0_SE11/PTA8/FTM1_CH0/RMII0_MDC/MII0_MDC/FTM1_QD_PHA/TPM1_CH0/TRACE_D2}
  - {pin_num: H9, peripheral: TPM1, signal: 'CH, 1', pin_signal: ADC0_SE9/ADC1_SE9/TSI0_CH6/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/SDRAM_RAS_b/FTM1_QD_PHB/TPM1_CH1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* Port A Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortA);
    /* Port B Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortB);
    /* Port C Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortC);
    /* Port D Clock Gate Control: Clock enabled */
    CLOCK_EnableClock(kCLOCK_PortD);

    gpio_pin_config_t brd_led_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTC5 (pin D8)  */
    GPIO_PinInit(BOARD_INITPINS_brd_led_GPIO, BOARD_INITPINS_brd_led_PIN, &brd_led_config);

    gpio_pin_config_t led0_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD0 (pin A5)  */
    GPIO_PinInit(BOARD_INITPINS_led0_GPIO, BOARD_INITPINS_led0_PIN, &led0_config);

    gpio_pin_config_t led1_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD1 (pin D4)  */
    GPIO_PinInit(BOARD_INITPINS_led1_GPIO, BOARD_INITPINS_led1_PIN, &led1_config);

    gpio_pin_config_t led2_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD2 (pin C4)  */
    GPIO_PinInit(BOARD_INITPINS_led2_GPIO, BOARD_INITPINS_led2_PIN, &led2_config);

    gpio_pin_config_t led3_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD3 (pin B4)  */
    GPIO_PinInit(BOARD_INITPINS_led3_GPIO, BOARD_INITPINS_led3_PIN, &led3_config);

    gpio_pin_config_t led4_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD4 (pin A4)  */
    GPIO_PinInit(BOARD_INITPINS_led4_GPIO, BOARD_INITPINS_led4_PIN, &led4_config);

    gpio_pin_config_t led5_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD5 (pin A3)  */
    GPIO_PinInit(BOARD_INITPINS_led5_GPIO, BOARD_INITPINS_led5_PIN, &led5_config);

    gpio_pin_config_t led6_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD6 (pin A2)  */
    GPIO_PinInit(BOARD_INITPINS_led6_GPIO, BOARD_INITPINS_led6_PIN, &led6_config);

    gpio_pin_config_t led7_config = {
        .pinDirection = kGPIO_DigitalOutput,
        .outputLogic = 0U
    };
    /* Initialize GPIO functionality on pin PTD7 (pin A1)  */
    GPIO_PinInit(BOARD_INITPINS_led7_GPIO, BOARD_INITPINS_led7_PIN, &led7_config);

    /* PORTA8 (pin K8) is configured as TPM1_CH0 */
    PORT_SetPinMux(PORTA, 8U, kPORT_MuxAlt6);

    /* PORTB1 (pin H9) is configured as TPM1_CH1 */
    PORT_SetPinMux(PORTB, 1U, kPORT_MuxAlt6);

    /* PORTC5 (pin D8) is configured as PTC5 */
    PORT_SetPinMux(BOARD_INITPINS_brd_led_PORT, BOARD_INITPINS_brd_led_PIN, kPORT_MuxAsGpio);

    /* PORTD0 (pin A5) is configured as PTD0 */
    PORT_SetPinMux(BOARD_INITPINS_led0_PORT, BOARD_INITPINS_led0_PIN, kPORT_MuxAsGpio);

    /* PORTD1 (pin D4) is configured as PTD1 */
    PORT_SetPinMux(BOARD_INITPINS_led1_PORT, BOARD_INITPINS_led1_PIN, kPORT_MuxAsGpio);

    /* PORTD2 (pin C4) is configured as PTD2 */
    PORT_SetPinMux(BOARD_INITPINS_led2_PORT, BOARD_INITPINS_led2_PIN, kPORT_MuxAsGpio);

    /* PORTD3 (pin B4) is configured as PTD3 */
    PORT_SetPinMux(BOARD_INITPINS_led3_PORT, BOARD_INITPINS_led3_PIN, kPORT_MuxAsGpio);

    /* PORTD4 (pin A4) is configured as PTD4 */
    PORT_SetPinMux(BOARD_INITPINS_led4_PORT, BOARD_INITPINS_led4_PIN, kPORT_MuxAsGpio);

    /* PORTD5 (pin A3) is configured as PTD5 */
    PORT_SetPinMux(BOARD_INITPINS_led5_PORT, BOARD_INITPINS_led5_PIN, kPORT_MuxAsGpio);

    /* PORTD6 (pin A2) is configured as PTD6 */
    PORT_SetPinMux(BOARD_INITPINS_led6_PORT, BOARD_INITPINS_led6_PIN, kPORT_MuxAsGpio);

    /* PORTD7 (pin A1) is configured as PTD7 */
    PORT_SetPinMux(BOARD_INITPINS_led7_PORT, BOARD_INITPINS_led7_PIN, kPORT_MuxAsGpio);

    SIM->SOPT9 = ((SIM->SOPT9 &
                   /* Mask bits to zero which are setting */
                   (~(SIM_SOPT9_TPM1CH0SRC_MASK)))

                  /* TPM1 channel 0 input capture source select: TPM1_CH0 signal. */
                  | SIM_SOPT9_TPM1CH0SRC(SOPT9_TPM1CH0SRC_TPM));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
